<a href="https://colab.research.google.com/github/wojtekgradzinski/Playground/blob/main/Copy_of_Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [20]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.7.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [21]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [9]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [22]:
from sklearn.model_selection  import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [23]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [24]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [25]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [26]:
ann.add(tf.keras.layers.Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [27]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error' )

### Training the ANN model on the Training set

In [28]:
ann.fit(X_train, y_train, batch_size = 32 , epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 187327.9219
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 1387.8385
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 171.4373
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 168.9389
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 166.4722
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 164.1348
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 161.4185
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 158.4594
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 155.6719
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 151.7858
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 148.0298
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - 

### Predicting the results of the Test set

In [34]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 2)
np.concatenate((y_pred.reshape(len(y_pred), 1) , y_test.reshape(len(y_test), 1)), 1)       #changing from horizontal to vertical  . For horizontal concatenate use 0 for verticl use 1

array([[429.35, 431.23],
       [460.53, 460.01],
       [464.13, 461.14],
       ...,
       [471.15, 473.26],
       [438.33, 438.  ],
       [457.37, 463.28]])